// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toInt(x) {
  return x;
}

function fromInt(x) {
  return x;
}

var BaseInt = {
  toInt: toInt,
  fromInt: fromInt
};

var Age = {
  toInt: toInt,
  fromInt: fromInt
};

var Price = {
  toInt: toInt,
  fromInt: fromInt
};

function getPrice(param) {
  return 200;
}

var token = {
  age: 200,
  price: 10
};

var age = 10;

exports.BaseInt = BaseInt;
exports.Age = Age;
exports.Price = Price;
exports.getPrice = getPrice;
exports.token = token;
exports.age = age;
/* No side effect */
