// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(x) {
  return x;
}

function fromString(x) {
  return x;
}

var BaseString = {
  toString: toString,
  fromString: fromString
};

var addressRegexp = new RegExp("^((bitcoincash:)?(q|p)[a-z0-9]{41})");

function fromString$1(address) {
  if (addressRegexp.test(address)) {
    return address;
  }
  throw {
        RE_EXN_ID: "Invalid_argument",
        _1: "",
        Error: new Error()
      };
}

var CashAddress = {
  toString: toString,
  addressRegexp: addressRegexp,
  fromString: fromString$1
};

var token_address2 = fromString$1("hggjgh");

var token = {
  address: "hggjgh",
  address2: token_address2
};

function converCashAdress(address) {
  return address;
}

console.log("ldjhgusdgugfb");

exports.BaseString = BaseString;
exports.CashAddress = CashAddress;
exports.token = token;
exports.converCashAdress = converCashAdress;
/* addressRegexp Not a pure module */
